### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by bacardi55** [abeudin/etherpadlite_ynh#6]
I tried to install etherpad via this repo but i couldn't access it after the install was successful. I have a 

```
nginx error: bad getway 
```

and found this in the logs:

```
2014/12/09 12:55:55 [error] 23356#0: *30244 connect() failed (111: Connection refused) while connecting to upstream, client: X.X.X.X, server: …, request: "GET /pad/ HTTP/1.1", upstream: "http://127.0.0.1:9001/", host: "…", referrer: "https://…"
```

In etherpad logs, I have these:

```
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json ejs@0.6.1 No repository field.
npm WARN package.json formidable@1.0.9 No repository field.
npm WARN package.json jsdom-nocontextifiy@0.2.10 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
ensure custom css/js files are created...
start...
[2014-12-09 13:03:52.209] [ERROR] console - ERROR: Problem while initalizing the database
[2014-12-09 13:03:52.211] [ERROR] console - Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
    --------------------
    at Protocol._enqueue (/var/www/etherpadlite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/var/www/etherpadlite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/var/www/etherpadlite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:109:18)
    at Connection._implyConnect (/var/www/etherpadlite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:387:10)
    at Connection.query (/var/www/etherpadlite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:174:8)
    at exports.database.init (/var/www/etherpadlite/src/node_modules/ueberDB/mysql_db.js:59:6)
    at exports.database.init (/var/www/etherpadlite/src/node_modules/ueberDB/CacheAndBufferLayer.js:110:18)
    at exports.database.init (/var/www/etherpadlite/src/node_modules/ueberDB/CloneAndAtomicLayer.js:48:11)
    at Object.exports.init (/var/www/etherpadlite/src/node/db/DB.js:41:6)
    at async.waterfall.hooks.aCallAll.settings (/var/www/etherpadlite/src/node/server.js:62:8)
RESTART!
```

PS: this is a copy of what i posted here https://forum.yunohost.org/t/etherpad-lite-package/68/9 . Thought it make more sens to post it here :)
I tried it twice. Once in public and one in private one. Didn't work in both case.

**Comment by matthewdavis** [comment]
Any chance to look at this yet?

**Comment by m2f0u4d** [comment]
just changed the nodejs installation source in my fork
now it works as expected

**Comment by raf64flo** [comment]
Hello @abeudin 

I've installed Etherpad lite for Yunohost on a Raspberry Pi 2, the install came successful but the Pad  crashes a start with following message:

```
You're running a wrong version of node, or io.js is not installed. You're using v0.6.19, we need v0.10.x, v0.11.x or v0.12.x
RESTART!
```

Tried to install io.js: 

```
# npm install iojs
npm http GET https://registry.npmjs.org/iojs
npm ERR! Error: failed to fetch from registry: iojs
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:209:10)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at CleartextStream.socketErrorListener (http.js:1188:9)
npm ERR!     at CleartextStream.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /var/log/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 4.1.6-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "iojs"
npm ERR! cwd /var/log
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: iojs
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/log/npm-debug.log
npm not ok
```

Any help appreciated.

**Comment by stevenroose** [comment]
I also get the 502 Bad Gateway error after installation. Anyone aware of a solution?
